name: Run Selenium On GitHub Action
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 18 * * 2,3'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.14
      - name: Installing package list
        run: apt list --installed
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable

       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: |
          sudo apt-get install fonts-ipafont fonts-ipaexfont

      - name: Running the Python script
        run: |
          ./fetch_vangohan.py -o docs
          ./fetch_vangohan.py -o docs -l en

      - name: Commit and Push The Results From Python Selenium Action
        if: github.ref == 'refs/heads/main'
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "GitHub Actions Results added"
         git push
